"""Script to rewrite the economic impact sections of write_report.py."""

with open('scripts/write_report.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find start and end indices
start_idx = -1
end_idx = -1
for i, line in enumerate(lines):
    if "# ECONOMIC IMPACT - PERTH COUNTY" in line:
        start_idx = i - 1
    elif "# COMBINED ECONOMIC COMPARISON" in line:
        end_idx = i - 1

if start_idx == -2 or end_idx == -2:
    print("Could not find boundaries")
    exit(1)

new_content = [
    "# =========================================================================\n",
    "# ECONOMIC IMPACT - PERTH COUNTY\n",
    "# =========================================================================\n",
    "new_doc.add_page_break()\n",
    "new_doc.add_heading('Economic Impact of the Agri-Food Sector in Perth County', level=2)\n",
    "\n",
    "new_doc.add_paragraph(\n",
    "    'The agricultural profile in the previous section describes what happens on Perth County\\'s farms — the '\n",
    "    'crops, livestock, and people that make up the primary production sector. But the ultimate economic footprint of '\n",
    "    'this agriculture extends far beyond the farm gate. When a dairy farmer ships milk to a processing plant, '\n",
    "    'or when a grain elevator handles locally grown corn, each of these activities generates economic value '\n",
    "    'and employment further down the supply chain.'\n",
    ")\n",
    "\n",
    "new_doc.add_heading('What is the Agri-Food Value Chain Attribution Model?', level=3)\n",
    "new_doc.add_paragraph(\n",
    "    'To capture this full picture, the Ontario Ministry of Agriculture, Food and Agribusiness (OMAFA) utilizes '\n",
    "    'an economic attribution model to measure the impact of the entire agri-food value chain. This model tracks '\n",
    "    'three interconnected stages:'\n",
    ")\n",
    "new_doc.add_paragraph(\n",
    "    '1. Primary Agriculture (Farming): The raw commodities produced on local farms.\\n'\n",
    "    '2. Food, Beverage and Tobacco Manufacturing: The secondary processing of those raw agricultural products.\\n'\n",
    "    '3. Food Retail: The final sale of finished food products to consumers.'\n",
    ")\n",
    "new_doc.add_paragraph(\n",
    "    'Crucially, the OMAFA attribution model measures the total economic activity and jobs supported throughout '\n",
    "    'the entire province of Ontario that can be directly attributed back to the agricultural production in a '\n",
    "    'specific county. For example, a pig raised on a farm in Perth County might support a truck driving job '\n",
    "    'transporting it, a meat-packing job at a processing facility in another region, and a retail job at a grocery '\n",
    "    'store in Toronto. The OMAFA data rolls all of these province-wide downstream impacts up and attributes '\n",
    "    'them back to the county where the raw agricultural product originated.'\n",
    ")\n",
    "\n",
    "new_doc.add_heading('Perth County: Feeding the Province', level=3)\n",
    "new_doc.add_paragraph(\n",
    "    'In 2024, the primary agricultural output from Perth County farms ultimately generated $2.98 billion in '\n",
    "    'agri-food GDP across Ontario. This makes Perth County the third-largest economic driver of Ontario\\'s '\n",
    "    'agri-food system among all counties and regions, trailing only Essex ($4.06 billion) and Huron ($3.58 '\n",
    "    'billion). The farm production from this single county is responsible for supporting 5.8% of Ontario\\'s '\n",
    "    'entire $51.4 billion agri-food GDP.'\n",
    ")\n",
    "\n",
    "add_styled_table(new_doc,\n",
    "    ['Year', 'Agri-Food GDP ($M)', 'Employment (Jobs)'],\n",
    "    [\n",
    "        ['2012', '$2,204.6', '39,957'],\n",
    "        ['2014', '$2,439.8', '42,779'],\n",
    "        ['2016', '$2,522.9', '43,742'],\n",
    "        ['2017', '$2,666.0', '45,273'],\n",
    "        ['2019', '$2,798.4', '47,070'],\n",
    "        ['2020', '$2,593.1', '39,572'],\n",
    "        ['2022', '$2,907.3', '45,490'],\n",
    "        ['2023', '$2,970.2', '47,487'],\n",
    "        ['2024', '$2,983.8', 'N/A'],\n",
    "    ]\n",
    ")\n",
    "\n",
    "new_doc.add_paragraph(\n",
    "    'Over the 12-year period from 2012 to 2024, the province-wide GDP attributed to Perth County\\'s agri-food '\n",
    "    'sector grew by 35.3%, representing a compound annual growth rate (CAGR) of 2.6%. All GDP figures are '\n",
    "    'expressed in chained 2017 dollars, meaning they have been adjusted for inflation. This real, inflation-adjusted '\n",
    "    'growth demonstrates that the county\\'s agricultural base is genuinely expanding its productive capacity and '\n",
    "    'creating more downstream value—not simply benefiting from rising market prices.'\n",
    ")\n",
    "\n",
    "new_doc.add_heading('Agri-Food Employment Footprint', level=3)\n",
    "new_doc.add_paragraph(\n",
    "    'In 2023, the agricultural output from Perth County supported approximately 47,487 jobs across the province. '\n",
    "    'These 47,487 jobs represent 5.5% of Ontario\\'s total agri-food workforce spanning farm operators, processing '\n",
    "    'technicians, and supply chain logistics professionals.'\n",
    ")\n",
    "new_doc.add_paragraph(\n",
    "    'It is important to understand that while these jobs are distributed throughout the provincial economy, Perth '\n",
    "    'County itself serves as a highly integrated hub. The county captures a significant portion of this downstream '\n",
    "    'economic activity locally, anchored by a robust local food manufacturing and processing base around '\n",
    "    'communities like Stratford and Listowel. Facilities such as meat packers, dairy processors, and feed mills '\n",
    "    'operate within the county specifically because of their proximity to Perth\\'s world-class primary agricultural '\n",
    "    'output.'\n",
    ")\n",
    "\n",
    "new_doc.add_heading('Provincial Agri-Food GDP Rankings', level=3)\n",
    "\n",
    "add_styled_table(new_doc,\n",
    "    ['Rank', 'County/Region', '2024 Agri-Food GDP'],\n",
    "    [\n",
    "        ['1', 'Essex County', '$4,058.9M'],\n",
    "        ['2', 'Huron County', '$3,576.3M'],\n",
    "        ['3', 'Perth County', '$2,983.8M'],\n",
    "        ['4', 'Middlesex County', '$2,888.0M'],\n",
    "        ['5', 'Wellington County', '$2,692.1M'],\n",
    "        ['6', 'Oxford County', '$2,681.7M'],\n",
    "        ['7', 'Chatham-Kent', '$2,585.6M'],\n",
    "        ['8', 'Bruce County', '$1,814.7M'],\n",
    "        ['9', 'Lambton County', '$1,682.8M'],\n",
    "        ['10', 'Elgin County', '$1,424.0M'],\n",
    "    ]\n",
    ")\n",
    "\n",
    "# =========================================================================\n",
    "# ECONOMIC IMPACT - WELLINGTON COUNTY\n",
    "# =========================================================================\n",
    "new_doc.add_page_break()\n",
    "new_doc.add_heading('Economic Impact of the Agri-Food Sector in Wellington County', level=2)\n",
    "\n",
    "new_doc.add_paragraph(\n",
    "    'Wellington County\\'s farms are another indispensable engine of the provincial economy. Using the same OMAFA '\n",
    "    'attribution model—which measures the localized and downstream province-wide impact generated by a single '\n",
    "    'county\\'s agricultural output—Wellington County\\'s farm production was responsible for generating $2.69 '\n",
    "    'billion in Ontario agri-food GDP in 2024. This makes Wellington the fifth-largest agri-food economic driver '\n",
    "    'in the province, accounting for 5.2% of Ontario\\'s entire agri-food GDP.'\n",
    ")\n",
    "\n",
    "new_doc.add_heading('Agri-Food GDP Growth and Resilience', level=3)\n",
    "\n",
    "add_styled_table(new_doc,\n",
    "    ['Year', 'Agri-Food GDP ($M)', 'Employment (Jobs)'],\n",
    "    [\n",
    "        ['2012', '$2,037.0', '36,920'],\n",
    "        ['2014', '$2,401.0', '42,099'],\n",
    "        ['2016', '$2,244.2', '38,910'],\n",
    "        ['2017', '$2,339.0', '39,719'],\n",
    "        ['2019', '$2,205.1', '37,090'],\n",
    "        ['2020', '$2,225.0', '33,955'],\n",
    "        ['2022', '$2,624.3', '41,062'],\n",
    "        ['2023', '$2,681.1', '42,845'],\n",
    "        ['2024', '$2,692.1', 'N/A'],\n",
    "    ]\n",
    ")\n",
    "\n",
    "new_doc.add_paragraph(\n",
    "    'Wellington County\\'s attributed agri-food GDP has grown by 32.2% over the 2012 to 2024 period (a real '\n",
    "    'inflation-adjusted CAGR of 2.4%). The growth trajectory has seen some year-to-year fluctuations reflecting '\n",
    "    'the county\\'s specific commodity mix. Notably, the downstream supply chains anchored by Wellington\\'s '\n",
    "    'agri-food sector proved exceptionally resilient during the 2020 pandemic downturn. While many other counties '\n",
    "    'saw double-digit economic contractions, Wellington\\'s agri-food footprint continued to grow by 0.9%. The '\n",
    "    'sector has continued to expand strongly, posting back-to-back records in 2022, 2023, and 2024.'\n",
    ")\n",
    "\n",
    "new_doc.add_heading('Agri-Food Employment Footprint', level=3)\n",
    "new_doc.add_paragraph(\n",
    "    'In 2023, the agricultural output from Wellington County farms supported 42,845 jobs throughout Ontario\\'s '\n",
    "    'value chain (farming, processing, and retail) — the fifth-highest employment impact generated by any '\n",
    "    'county. These positions represent 4.9% of Ontario\\'s total agri-food workforce.'\n",
    ")\n",
    "new_doc.add_paragraph(\n",
    "    'Much like Perth County, Wellington County captures a massive share of this downstream economic activity '\n",
    "    'within its own geographic borders. The region, particularly in Guelph and Centre Wellington, is home to a '\n",
    "    'dense cluster of food manufacturing and agribusiness operations. This local processing ecosystem is uniquely '\n",
    "    'fortified by the presence of the University of Guelph—Canada\\'s premier agricultural university—which '\n",
    "    'provides a continuous pipeline of world-class agricultural research, technological innovation, and highly '\n",
    "    'skilled graduates.'\n",
    ")\n",
]

lines = lines[:start_idx] + new_content + lines[end_idx:]

# Also update the save filename to v5
for i, line in enumerate(lines):
    if "'Report_v4.docx'" in line:
        lines[i] = line.replace("'Report_v4.docx'", "'Report_v5.docx'")

with open('scripts/write_report.py', 'w', encoding='utf-8') as f:
    f.writelines(lines)

print("Report generator updated.")
