"""
Generate Developer Manual for the Fiscal Benchmarking — Peer Comparison section.
Produces a Word document (.docx) at the specified output path.

Usage:
    python scripts/generate_fiscal_manual.py
"""
from pathlib import Path
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = PROJECT_ROOT.parent.parent / "Reports and supplemental information" / "Rural Community Data Tabs"
OUTPUT_PATH = OUTPUT_DIR / "Fiscal Benchmarking Tab - Developer Manual.docx"


def _set_cell_shading(cell, color_hex: str):
    """Set background shading on a table cell."""
    shading = OxmlElement("w:shd")
    shading.set(qn("w:fill"), color_hex)
    shading.set(qn("w:val"), "clear")
    cell._tc.get_or_add_tcPr().append(shading)


def _add_table_row(table, cells: list, bold=False, header=False):
    """Add a row to a table with optional formatting."""
    row = table.add_row()
    for i, text in enumerate(cells):
        cell = row.cells[i]
        p = cell.paragraphs[0]
        run = p.add_run(str(text))
        run.font.size = Pt(9)
        if bold or header:
            run.bold = True
        if header:
            _set_cell_shading(cell, "2E86C1")
            run.font.color.rgb = RGBColor(255, 255, 255)


def build_manual():
    doc = Document()

    # ── Styles ──
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    # ── Title Page ──
    title = doc.add_heading("Fiscal Benchmarking — Peer Comparison", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph("Developer Manual", style="Subtitle").alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph(
        "Rural Community Data Dashboard\n"
        "Farm Finance Stats Dashboard\n\n"
        "Version: 1.0 (Post-Audit)\n"
        "Last Updated: 2026-02-26\n"
        "Audit Status: 🟢 GO — Cleared for Production"
    ).alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_page_break()

    # ── Table of Contents (manual) ──
    doc.add_heading("Table of Contents", level=1)
    toc_items = [
        "1. Architecture & Data Flow",
        "2. ETL Pipeline: process_fir.py",
        "3. Data Loader: _load_fir_as_long()",
        "4. BENCHMARK_INDICATORS Configuration",
        "5. UI Rendering: Scorecard, Charts, Export",
        "6. Helper Functions",
        "7. INDICATOR_META Reference",
        "8. Risk Band System",
        "9. Maintenance & Update Procedures",
        "10. Expert Audit History",
    ]
    for item in toc_items:
        doc.add_paragraph(item, style="List Number")
    doc.add_page_break()

    # ═══════════════════════════════════════════════════════════════════
    # 1. ARCHITECTURE
    # ═══════════════════════════════════════════════════════════════════
    doc.add_heading("1. Architecture & Data Flow", level=1)
    doc.add_paragraph(
        "The Fiscal Benchmarking section provides a consultant-grade peer comparison tool "
        "for municipal staff, CAOs, and Treasurers to benchmark one 'focus' municipality "
        "against up to 5 peers across 10 fiscal metrics derived from Ontario Financial "
        "Information Return (FIR) data."
    )
    doc.add_heading("Pipeline Architecture", level=2)
    doc.add_paragraph(
        "data/FIR Data/{year}/FI{yy}{code} {name}.zip  (raw FIR xlsx files)\n"
        "  → scripts/process_fir.py                     (calamine-based ETL)\n"
        "  → config/fir_indicators.yaml                 (schedule/line/col definitions)\n"
        "  → config/fir_sgc_crosswalk.csv               (FIR code → SGC code mapping)\n"
        "  → data/derived/fir_indicators.csv             (wide-format output)\n"
        "  → app/pages/9_🏘️_Rural_Community_Data.py\n"
        "      → _load_fir_as_long()  melts to long format\n"
        "      → load_fir_indicators()  caches long-format data\n"
        "      → §7b Fiscal Benchmarking section (UI rendering)",
        style="No Spacing"
    )

    doc.add_heading("Data Sources", level=2)
    tbl = doc.add_table(rows=1, cols=4)
    tbl.style = "Light Grid Accent 1"
    for i, h in enumerate(["Source", "Format", "Update Frequency", "Notes"]):
        tbl.rows[0].cells[i].text = h
    data_sources = [
        ("Ontario FIR Data", "ZIP → XLSX", "Annual (MMAH release)", "Manual download from Ontario Data Catalogue"),
        ("fir_sgc_crosswalk.csv", "CSV", "As needed", "Maps FIR 4-digit codes to 7-digit SGC codes"),
        ("fir_indicators.yaml", "YAML", "When new indicators added", "Defines schedule, line code, column for each indicator"),
        ("fir_indicators.csv", "CSV (wide)", "Generated by ETL", "~2,134 rows × 80+ columns per year batch"),
    ]
    for row_data in data_sources:
        row = tbl.add_row()
        for i, val in enumerate(row_data):
            row.cells[i].text = val

    doc.add_page_break()

    # ═══════════════════════════════════════════════════════════════════
    # 2. ETL PIPELINE
    # ═══════════════════════════════════════════════════════════════════
    doc.add_heading("2. ETL Pipeline: process_fir.py", level=1)
    doc.add_paragraph(
        "The ETL pipeline extracts fiscal indicators from Ontario FIR xlsx files "
        "(packaged as ZIP archives) and produces a wide-format CSV. It uses "
        "python-calamine (a Rust-based xlsx reader) for 10-50x faster parsing "
        "than openpyxl, processing ~2,134 files in minutes."
    )

    doc.add_heading("Key Functions", level=2)
    functions = [
        ("_match_line_code(cell, line_code)", "Normalizes calamine cell values (str/float) to 4-digit zero-padded FIR line codes for matching."),
        ("_build_fir_col_map(rows)", "Scans first 25 rows of a schedule to build FIR column number → 0-based index mapping."),
        ("_extract_fir_value(rows, line_code, fir_col, ...)", "Extracts a value from sheet data using FIR column mapping."),
        ("_extract_from_sheet_data(rows, line_code, col_idx)", "Direct extraction by line code and column index (for 'excel' col_type)."),
        ("_safe_div(a, b)", "Safe division: returns None if either operand is None or denominator is 0."),
        ("_safe_float(val)", "A1 Audit Fix: safely cast to float, returning None for non-numeric/empty/None values."),
        ("_safe_add(*args)", "Sums non-None arguments; returns None only if ALL arguments are None."),
        ("_compute_derived(r)", "Core computation engine: computes 20+ derived ratios including all 10 BENCHMARK_INDICATORS."),
        ("extract_municipality(zip_path, indicator_config)", "Extracts all configured indicators from a single FIR ZIP file."),
        ("process_all(years, sample)", "Batch processor: iterates FIR ZIP files, merges SGC crosswalk."),
    ]
    tbl = doc.add_table(rows=1, cols=2)
    tbl.style = "Light Grid Accent 1"
    tbl.rows[0].cells[0].text = "Function"
    tbl.rows[0].cells[1].text = "Purpose"
    for fname, purpose in functions:
        row = tbl.add_row()
        row.cells[0].text = fname
        row.cells[1].text = purpose

    doc.add_heading("Three Extraction Modes", level=2)
    doc.add_paragraph(
        '1. "fir" (default) — Uses _build_fir_col_map to find header columns, then '
        "_extract_fir_value for data rows. Used for most schedules.\n"
        '2. "rtc" (Schedule 22A) — Matches on Realty Tax Class string (RT, FT, CT, etc.) '
        "rather than line codes.\n"
        '3. "excel" — Direct 1-based Excel column index. Used when FIR column headers are absent.',
    )

    doc.add_heading("SGC Crosswalk", level=2)
    doc.add_paragraph(
        "The crosswalk file (config/fir_sgc_crosswalk.csv) maps 4-digit FIR municipality codes "
        "to 7-digit StatCan SGC codes. A left join is used so all FIR records are retained, "
        "but unmatched codes produce sgc_code=NaN and are excluded from the dashboard. "
        "Q15 Audit Fix: Unmapped codes are now logged with warnings during ETL."
    )
    doc.add_page_break()

    # ═══════════════════════════════════════════════════════════════════
    # 3. DATA LOADER
    # ═══════════════════════════════════════════════════════════════════
    doc.add_heading("3. Data Loader: _load_fir_as_long()", level=1)
    doc.add_paragraph(
        "Converts the wide-format fir_indicators.csv into long-format (sgc_code, census_year, "
        "indicator, value) compatible with the generic tabbed indicator renderer."
    )
    doc.add_paragraph(
        "Key steps:\n"
        "1. Read CSV, coerce sgc_code to numeric, drop NaN, zero-pad to 7 digits\n"
        "2. Filter to Ontario ('35' prefix)\n"
        "3. Melt from wide to long using FIR_INDICATOR_COLS\n"
        "4. Rename 'year' → 'census_year' (Tech Debt TODO: rename to 'reporting_year')\n"
        "5. Drop rows with NaN values\n"
        "6. Cached via @st.cache_data(ttl=3600)"
    )
    doc.add_page_break()

    # ═══════════════════════════════════════════════════════════════════
    # 4. BENCHMARK INDICATORS
    # ═══════════════════════════════════════════════════════════════════
    doc.add_heading("4. BENCHMARK_INDICATORS Configuration", level=1)
    doc.add_paragraph(
        "The 10 consultant-grade metrics used in the Fiscal Scorecard, bar chart, "
        "and trend chart. Each is a tuple of (slug, display_name, unit, risk_bands)."
    )
    tbl = doc.add_table(rows=1, cols=5)
    tbl.style = "Light Grid Accent 1"
    for i, h in enumerate(["#", "Metric", "Unit", "ETL Formula", "Risk Bands"]):
        tbl.rows[0].cells[i].text = h
    indicators = [
        ("1", "Asset Consumption Ratio", "pct", "TCA Amort ÷ TCA Historical Cost", "≤50% Low / ≤75% Mod / >75% High"),
        ("2", "Staffing Intensity", "pct", "Salaries & Benefits ÷ Total Expenses", "None"),
        ("3", "Cash Operating Margin", "pct", "(Rev − Exp + Amort) ÷ Rev [floor: $1K]", "None"),
        ("4", "Debt-to-Revenue", "pct", "Long-Term Debt ÷ Total Revenue", "≤25% Healthy / ≤50% Mod / >50% Tight"),
        ("5", "Avg Tax / Household", "$", "(Res + Multi-Res Muni Tax) ÷ Households", "None"),
        ("6", "Reserves-to-Revenue", "pct", "(Reserves + Reserve Funds) ÷ Revenue", "None"),
        ("7", "Capital Reinvestment Rate", "pct", "Capital Additions ÷ Revenue", "None"),
        ("8", "OMPF Dependency", "pct", "OMPF Grant ÷ Total Revenue", "None"),
        ("9", "User Fee Reliance", "pct", "User Fees & Charges ÷ Revenue", "None"),
        ("10", "Accounting Surplus (Accrual)", "$", "Total Revenue − Total Expenses", "None"),
    ]
    for row_data in indicators:
        row = tbl.add_row()
        for i, val in enumerate(row_data):
            row.cells[i].text = val

    doc.add_paragraph("")
    p = doc.add_paragraph()
    run = p.add_run("IMPORTANT: ")
    run.bold = True
    run.font.color.rgb = RGBColor(231, 76, 60)
    p.add_run(
        "Metric #10 'Accounting Surplus' is a PSAB accrual-based figure. "
        "It includes non-cash items (amortization) and capital grants, and does NOT "
        "represent cash available to the municipality. A dedicated UI caveat is displayed."
    )
    doc.add_page_break()

    # ═══════════════════════════════════════════════════════════════════
    # 5. UI RENDERING
    # ═══════════════════════════════════════════════════════════════════
    doc.add_heading("5. UI Rendering", level=1)

    doc.add_heading("5.1 Year & Peer Selection", level=2)
    doc.add_paragraph(
        "• Year selector labeled 'FIR Reporting Year' (not 'Census Year')\n"
        "• Focus municipality = first selected community (selected_codes[0])\n"
        "• Q8 Audit Fix: If focus has no FIR data, an explicit st.error() is shown\n"
        "• Peer multiselect: up to 5 peers, defaults to other selected communities"
    )

    doc.add_heading("5.2 Fiscal Scorecard Table", level=2)
    doc.add_paragraph(
        "• Q7 Audit Fix: Raw numeric values stored in DataFrame, formatted via st.column_config\n"
        "• Percentages pre-multiplied by 100 for Streamlit's '%.1f%%' format string\n"
        "• Focus row highlighted with blue background via Pandas Styler\n"
        "• Note: Requires Streamlit >= 1.30 for Styler + column_config compatibility\n"
        "• Q16 Audit Fix: pivot_table uses aggfunc='last' for deterministic ordering"
    )

    doc.add_heading("5.3 Risk Band Legend", level=2)
    doc.add_paragraph(
        "• Q10 Audit Fix: math.inf sentinels filtered from legend display\n"
        "• Highest band rendered as '> previous threshold' (e.g., '>75%')\n"
        "• Uses inline HTML with unsafe_allow_html=True"
    )

    doc.add_heading("5.4 Bar Chart", level=2)
    doc.add_paragraph(
        "• Horizontal bars sorted ascending by value\n"
        "• Focus municipality = dark blue (#2e86c1), peers = light blue (#85c1e9)\n"
        "• Risk threshold vlines drawn only for math.isfinite() thresholds\n"
        "• Q11 Audit Fix: Right margin increased to r=150, cliponaxis=False\n"
        "• Text labels via textposition='outside'"
    )

    doc.add_heading("5.5 Trend Chart", level=2)
    doc.add_paragraph(
        "• Multi-year line chart using plotly.express.line\n"
        "• Focus line: width=4, solid; Peer lines: width=1.5, dotted\n"
        "• Q12 Audit Fix: Risk bands fetched directly from BENCHMARK_INDICATORS config\n"
        "  (not aliased from bar chart variable) — true decoupling\n"
        "• X-axis labeled 'FIR Reporting Year'"
    )

    doc.add_heading("5.6 CSV Export", level=2)
    doc.add_paragraph(
        "• Raw numeric values (not formatted strings) in CSV\n"
        "• Note: 'pct' values are stored as raw decimals (0.45 = 45%), not pre-multiplied\n"
        "• 'Is Focus' column is boolean (True/False)\n"
        "• Filename: fiscal_benchmark_{municipality}_{year}.csv"
    )
    doc.add_page_break()

    # ═══════════════════════════════════════════════════════════════════
    # 6. HELPER FUNCTIONS
    # ═══════════════════════════════════════════════════════════════════
    doc.add_heading("6. Helper Functions", level=1)

    doc.add_heading("_format_value(val, unit)", level=2)
    tbl = doc.add_table(rows=1, cols=3)
    tbl.style = "Light Grid Accent 1"
    for i, h in enumerate(["Unit", "Input Example", "Output"]):
        tbl.rows[0].cells[i].text = h
    fmt_rows = [
        ("$", "1234567", "$1,234,567"),
        ("pct", "0.452", "45.2%"),
        ("ratio", "0.2177", "0.2177"),
        ("%", "45.2", "45.2%"),
        ("rate", "0.005231", "0.5231%"),
        ("km", "128.5", "128.5 km"),
    ]
    for row_data in fmt_rows:
        row = tbl.add_row()
        for i, val in enumerate(row_data):
            row.cells[i].text = val

    doc.add_heading("_safe_div(a, b)", level=2)
    doc.add_paragraph("Returns a/b if both non-None and b≠0. Otherwise None.")

    doc.add_heading("_safe_float(val)", level=2)
    doc.add_paragraph(
        "A1 Audit Fix: Safely converts to float. Returns None for None, empty strings, "
        "'NA', and non-numeric values. Prevents TypeError crashes in _compute_derived()."
    )

    doc.add_heading("_safe_add(*args)", level=2)
    doc.add_paragraph(
        "Sums all non-None arguments. Returns None only if ALL arguments are None. "
        "This means missing reserves (None) are treated as 'unknown', not '$0'. "
        "If one component is present, it's returned as the total."
    )
    doc.add_page_break()

    # ═══════════════════════════════════════════════════════════════════
    # 7. INDICATOR_META REFERENCE
    # ═══════════════════════════════════════════════════════════════════
    doc.add_heading("7. INDICATOR_META Reference (Municipal Finance)", level=1)
    doc.add_paragraph(
        "The following indicators are registered in INDICATOR_META under the 'Municipal Finance' "
        "category and appear in the generic tabbed indicator views."
    )
    meta_entries = [
        ("total_revenue", "$", "Total Revenue"), ("total_expenses", "$", "Total Expenses"),
        ("operating_surplus", "$", "Accounting Surplus/Deficit"),
        ("own_purpose_tax_rev", "$", "Own-Purpose Tax Revenue"),
        ("total_taxable_cva", "$", "Total Taxable CVA"),
        ("accumulated_surplus", "$", "Accumulated Surplus"),
        ("net_financial_assets", "$", "Net Financial Assets"),
        ("ompf_grant", "$", "OMPF Grant"), ("ompf_dependency", "pct", "OMPF Dependency"),
        ("ompf_relief_factor", "ratio", "OMPF Relief Factor"),
        ("debt_interest", "$", "Debt Interest"), ("tax_arrears_ratio", "ratio", "Tax Arrears Ratio"),
        ("total_road_km", "km", "Total Road KM"), ("paved_road_km", "km", "Paved Roads"),
        ("total_reserves_and_funds", "$", "Total Reserves + Reserve Funds"),
        ("reserves_to_revenue", "pct", "Reserves-to-Revenue Ratio"),
        ("capital_reinvestment_rate", "pct", "Capital Reinvestment Rate"),
        ("user_fee_reliance", "pct", "User Fee Reliance"),
        ("asset_consumption_ratio", "pct", "Asset Consumption Ratio"),
        ("staffing_intensity", "pct", "Staffing Intensity"),
        ("cash_operating_margin", "pct", "Cash Operating Margin"),
        ("avg_tax_per_household", "$", "Avg Tax per Household"),
        ("total_long_term_debt", "$", "Total Long-Term Debt"),
        ("debt_to_revenue", "pct", "Debt-to-Revenue Ratio"),
    ]
    tbl = doc.add_table(rows=1, cols=3)
    tbl.style = "Light Grid Accent 1"
    for i, h in enumerate(["Slug", "Unit", "Display Name"]):
        tbl.rows[0].cells[i].text = h
    for slug, unit, name in meta_entries:
        row = tbl.add_row()
        row.cells[0].text = slug
        row.cells[1].text = unit
        row.cells[2].text = name
    doc.add_page_break()

    # ═══════════════════════════════════════════════════════════════════
    # 8. RISK BAND SYSTEM
    # ═══════════════════════════════════════════════════════════════════
    doc.add_heading("8. Risk Band System", level=1)
    doc.add_paragraph(
        "Risk bands follow MMAH Financial Indicator Review / BMA Municipal Study standards. "
        "Only two metrics currently have risk bands; others can be added as tuples."
    )
    doc.add_heading("Implementation Details", level=2)
    doc.add_paragraph(
        "• Sentinel: math.inf is used for the highest (unbounded) band\n"
        "• Chart vlines: Only drawn for math.isfinite() thresholds\n"
        "• Legend: Highest band shows '> previous threshold' (e.g., '>75%')\n"
        "• Adding a new risk band: Add a tuple (threshold, label, hex_color) to the band list\n"
        "• Thresholds are in decimal form (0.50 = 50%)"
    )
    doc.add_page_break()

    # ═══════════════════════════════════════════════════════════════════
    # 9. MAINTENANCE
    # ═══════════════════════════════════════════════════════════════════
    doc.add_heading("9. Maintenance & Update Procedures", level=1)

    doc.add_heading("9.1 Annual FIR Data Update", level=2)
    doc.add_paragraph(
        "1. Download new year's FIR ZIP files from Ontario Data Catalogue\n"
        "2. Place in data/FIR Data/{year}/ directory\n"
        "3. Run: python scripts/process_fir.py --year {year}\n"
        "4. Check console output for:\n"
        "   - Record count and extraction rate\n"
        "   - Columns with >10% null rates\n"
        "   - SGC crosswalk unmapped codes (Q15 warnings)\n"
        "5. Verify data in dashboard"
    )

    doc.add_heading("9.2 SGC Crosswalk Maintenance", level=2)
    doc.add_paragraph(
        "When new municipalities are created or amalgamated:\n"
        "1. Check ETL warnings for unmapped FIR codes\n"
        "2. Add new entries to config/fir_sgc_crosswalk.csv\n"
        "3. Re-run ETL for affected years"
    )

    doc.add_heading("9.3 Adding New BENCHMARK_INDICATORS", level=2)
    doc.add_paragraph(
        "1. Add the ETL extraction to config/fir_indicators.yaml (schedule, line, col)\n"
        "2. Add derived computation to _compute_derived() in process_fir.py\n"
        "3. Add column name to FIR_INDICATOR_COLS in the UI file\n"
        "4. Add INDICATOR_META entry with (display_name, unit, 'Municipal Finance')\n"
        "5. Add tuple to BENCHMARK_INDICATORS: (slug, display_name, unit, risk_bands_or_None)\n"
        "6. Re-run ETL to generate new column"
    )

    doc.add_heading("9.4 Known Tech Debt", level=2)
    doc.add_paragraph(
        "• Q14: Internal column name 'census_year' should be renamed to 'reporting_year' "
        "in the next major version cycle. Currently kept for generic tab renderer compatibility.\n"
        "• Streamlit version: Requires >= 1.30 for Styler + column_config harmonization."
    )
    doc.add_page_break()

    # ═══════════════════════════════════════════════════════════════════
    # 10. AUDIT HISTORY
    # ═══════════════════════════════════════════════════════════════════
    doc.add_heading("10. Expert Audit History", level=1)
    doc.add_paragraph(
        "This section was reviewed by an expert red team AI specializing in "
        "municipal finance, MMAH FIR data, BMA Municipal Studies, and dashboard QA."
    )

    doc.add_heading("Round 1 Verdict: 🚨 NO-GO", level=2)
    doc.add_paragraph(
        "22 findings identified (Q1-Q20 + A1-A2):\n"
        "• P0 (Critical): Q6 (accrual surplus mislabeling), Q14 (census_year), A1 (float crash)\n"
        "• P1 (High): Q1/Q3 (unit mismatch), Q7 (sorting), Q8 (focus KeyError), Q15 (crosswalk), "
        "Q16 (aggfunc), Q19 (bounds), A2 (debt coalescing)\n"
        "• P2 (Moderate): Q4 (div/0), Q10 (sentinel), Q11 (clipping), Q12 (coupling), Q17 (label)\n"
        "• P3 (Low): Q2, Q5, Q9, Q13, Q18, Q20 — working as intended"
    )

    doc.add_heading("Round 2 Verdict: 🟢 GO", level=2)
    doc.add_paragraph(
        "All 22 findings remediated. Sign-off matrix:\n"
        "• 13 of 14 remediations: PASS\n"
        "• 1 PARTIAL (Q12): Upgraded to true decoupling in post-signoff hotfix\n"
        "• Q14 compromise accepted: UI labels fixed, internal name kept with TODO"
    )

    tbl = doc.add_table(rows=1, cols=4)
    tbl.style = "Light Grid Accent 1"
    for i, h in enumerate(["Finding", "Priority", "Fix Summary", "Verdict"]):
        tbl.rows[0].cells[i].text = h
    audit_rows = [
        ("A1: float(None) crash", "P0", "_safe_float() helper", "PASS"),
        ("A2: Debt None→0", "P1", "Removed coalescing", "PASS"),
        ("Q1/Q3: Unit mismatch", "P1", "ratio → pct (BMA)", "PASS"),
        ("Q4: Cash margin div/0", "P2", "$1K revenue floor", "PASS"),
        ("Q6: Surplus label", "P0", "Accrual label + PSAB caveat", "PASS"),
        ("Q7: Scorecard sorting", "P1", "st.column_config", "PASS"),
        ("Q8: Focus KeyError", "P1", "Graceful st.error()", "PASS"),
        ("Q10: Legend sentinel", "P2", "math.isfinite filter", "PASS"),
        ("Q11: Chart clipping", "P2", "r=150, cliponaxis=False", "PASS"),
        ("Q12: Trend coupling", "P2", "True decoupling from config", "PASS"),
        ("Q14: census_year", "P0", "UI labels + TODO", "ACCEPTED"),
        ("Q15: SGC logging", "P1", "Warning logs for unmapped", "PASS"),
        ("Q16: aggfunc", "P1", "first → last", "PASS"),
        ("Q17: Year label", "P2", "FIR Reporting Year", "PASS"),
        ("Q19: Bounds/sentinel", "P1", "math.inf", "PASS"),
    ]
    for row_data in audit_rows:
        row = tbl.add_row()
        for i, val in enumerate(row_data):
            row.cells[i].text = val

    # ── Save ──
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    doc.save(str(OUTPUT_PATH))
    print(f"\n✓ Manual saved to: {OUTPUT_PATH}")


if __name__ == "__main__":
    build_manual()
