"""
PDF Community Profile Generator
================================
Generates a branded PDF community profile report with Census data,
trend charts, and peer comparisons. Can be called from the dashboard
or standalone.

Usage:
    python scripts/generate_pdf_report.py --sgc 3523008 --year 2021
"""

import argparse
import io
import sys
import tempfile
from pathlib import Path

import textwrap

import pandas as pd
import numpy as np

# Ensure project root is on path
project_root = Path(__file__).resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from fpdf import FPDF

# Red Team Fix Q3/Q4: Use shared engine (unified math for UI + PDF)
from app.similarity_engine import get_peer_communities

# Data paths
WELLBEING_DIR = project_root / "data" / "latest" / "wellbeing"
INDICATORS_FILE = WELLBEING_DIR / "census_indicators.csv"
GEO_FILE = WELLBEING_DIR / "dim_geography.csv"


# --- Indicator metadata (subset of what's in the dashboard) ---
INDICATOR_META = {
    "population":           ("Population",               ""),
    "pop_change_pct":       ("Population Change",        "%"),
    "pop_density":          ("Population Density",       "/km2"),
    "median_age":           ("Median Age",               "years"),
    "median_hh_income":     ("Median Household Income",  "$"),
    "median_hh_income_at":  ("Median After-Tax Income",  "$"),
    "unemployment_rate":    ("Unemployment Rate",        "%"),
    "employment_rate":      ("Employment Rate",          "%"),
    "participation_rate":   ("Participation Rate",       "%"),
    "low_income_pct":       ("Low Income Rate",          "%"),
    "avg_dwelling_value":   ("Avg Dwelling Value",       "$"),
    "shelter_cost_owned":   ("Shelter Cost (Owned)",     "$/mo"),
    "shelter_cost_rented":  ("Shelter Cost (Rented)",    "$/mo"),
    "unaffordable_renter_pct": ("Unaffordable Renters",  "%"),
    "avg_hh_size":          ("Avg Household Size",       ""),
    "pop_0_14":             ("Youth (0-14)",             ""),
    "pop_15_64":            ("Working Age (15-64)",      ""),
    "pop_65_plus":          ("Seniors (65+)",            ""),
    "owner_households":     ("Owner Households",         ""),
    "renter_households":    ("Renter Households",        ""),
    "commute_wfh":          ("Worked at Home",           ""),
    "postsecondary":        ("Postsecondary Education",  ""),
    "uni_bachelor_plus":    ("University (Bachelor+)",   ""),
    "indigenous_pop":       ("Indigenous Population",    ""),
    "immigrant_pop":        ("Immigrant Population",     ""),
}

# Key indicators for the snapshot table
SNAPSHOT_INDICATORS = [
    "population", "pop_change_pct", "median_age",
    "median_hh_income", "unemployment_rate", "low_income_pct",
    "avg_dwelling_value", "participation_rate",
    "pop_density", "avg_hh_size",
]

# Trend indicators to chart
TREND_INDICATORS = [
    "population", "median_hh_income", "unemployment_rate", "median_age",
]

# Brand colors
BRAND_DARK = (26, 82, 118)       # #1a5276
BRAND_ACCENT = (46, 134, 193)   # #2e86c1
BRAND_GREEN = (39, 174, 96)     # #27ae60
TEXT_COLOR = (30, 30, 30)
LIGHT_GREY = (240, 240, 240)
MED_GREY = (180, 180, 180)


class CommunityProfilePDF(FPDF):
    """Custom PDF class with branded header/footer."""

    def __init__(self, community_name: str, census_year: int, county: str = ""):
        super().__init__()
        self.community_name = community_name
        self.census_year = census_year
        self.county = county
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        # Brand bar at top
        self.set_fill_color(*BRAND_DARK)
        self.rect(0, 0, 210, 12, "F")
        self.set_fill_color(*BRAND_ACCENT)
        self.rect(0, 12, 210, 2, "F")

        # Header text
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 3)
        self.cell(0, 6, "Rural Ontario Community Profile", align="L")
        self.set_xy(10, 3)
        self.cell(0, 6, f"Census {self.census_year}", align="R")
        self.ln(18)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*MED_GREY)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | Data: Statistics Canada Census Profile | Generated by Rural Community Data Platform", align="C")

    def section_title(self, title: str):
        """Add a styled section header."""
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*BRAND_DARK)
        self.cell(0, 10, title, ln=True)
        # Underline
        self.set_draw_color(*BRAND_ACCENT)
        self.set_line_width(0.5)
        y = self.get_y()
        self.line(10, y, 200, y)
        self.ln(4)

    def subsection_title(self, title: str):
        """Add a subsection header."""
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*BRAND_ACCENT)
        self.cell(0, 7, title, ln=True)
        self.ln(1)

    def body_text(self, text: str):
        """Add body paragraph text."""
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*TEXT_COLOR)
        self.multi_cell(0, 5, text)
        self.ln(2)

    def add_data_table(self, headers: list, rows: list, col_widths: list = None):
        """Add a styled data table."""
        n_cols = len(headers)
        if col_widths is None:
            col_widths = [190 / n_cols] * n_cols

        # Header row
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(*BRAND_DARK)
        self.set_text_color(255, 255, 255)
        for i, (header, width) in enumerate(zip(headers, col_widths)):
            self.cell(width, 7, str(header), border=1, fill=True, align="C")
        self.ln()

        # Data rows
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*TEXT_COLOR)
        for j, row in enumerate(rows):
            if j % 2 == 0:
                self.set_fill_color(*LIGHT_GREY)
            else:
                self.set_fill_color(255, 255, 255)
            for i, (cell, width) in enumerate(zip(row, col_widths)):
                align = "L" if i == 0 else "R"
                self.cell(width, 6, str(cell), border=1, fill=True, align=align)
            self.ln()

    def add_mini_bar_chart(self, label: str, values: list, years: list):
        """Draw a simple horizontal bar chart in the PDF."""
        if not values or all(v is None for v in values):
            return

        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*TEXT_COLOR)
        self.cell(0, 5, label, ln=True)

        valid_values = [v for v in values if v is not None and not np.isnan(v)]
        if not valid_values:
            return

        max_val = max(abs(v) for v in valid_values) if valid_values else 1
        bar_max_width = 100

        for year, val in zip(years, values):
            if val is None or (isinstance(val, float) and np.isnan(val)):
                continue
            self.set_font("Helvetica", "", 7)
            self.cell(20, 5, str(year), align="R")
            self.cell(3)

            bar_width = (abs(val) / max_val * bar_max_width) if max_val > 0 else 0
            self.set_fill_color(*BRAND_ACCENT)
            self.rect(self.get_x(), self.get_y() + 1, bar_width, 3, "F")

            self.cell(bar_max_width + 5)
            self.set_font("Helvetica", "", 7)
            self.cell(0, 5, _format_value(val, INDICATOR_META.get(label, ("", ""))[1] if label in INDICATOR_META else ""), ln=True)

        self.ln(3)


def _format_value(val, unit):
    """Format a numeric value with its unit."""
    if val is None or (isinstance(val, float) and np.isnan(val)):
        return "--"
    if unit == "$":
        return f"${val:,.0f}"
    elif unit == "$/mo":
        return f"${val:,.0f}/mo"
    elif unit == "%":
        return f"{val:.1f}%"
    elif unit in ("years", "/km2", "km2"):
        return f"{val:,.1f} {unit}"
    elif abs(val) >= 1_000_000:
        return f"{val / 1_000_000:,.1f}M"
    elif abs(val) >= 1_000:
        return f"{val:,.0f}"
    else:
        return f"{val:,.1f}" if val != int(val) else f"{int(val):,}"


def load_data():
    """Load Census indicators and geography data."""
    if not INDICATORS_FILE.exists():
        raise FileNotFoundError(f"Census indicators not found at {INDICATORS_FILE}. Run the pipeline first.")

    indicators = pd.read_csv(INDICATORS_FILE)
    indicators["sgc_code"] = indicators["sgc_code"].astype(str).str.zfill(7)

    geo = pd.read_csv(GEO_FILE)
    geo["sgc_code"] = geo["sgc_code"].astype(str).str.zfill(7)

    return indicators, geo


def get_community_info(geo_df, sgc_code):
    """Get community name and county from geo data."""
    row = geo_df[geo_df["sgc_code"] == sgc_code]
    if row.empty:
        return sgc_code, ""
    name = row.iloc[0].get("geo_name", sgc_code)
    county = row.iloc[0].get("county", "")
    return str(name), str(county) if pd.notna(county) else ""




def generate_pdf(sgc_code: str, census_year: int = None, output_path: str = None) -> bytes:
    """
    Generate a PDF community profile report.

    Args:
        sgc_code: 7-digit SGC code
        census_year: Census year to focus on (default: latest available)
        output_path: Optional file path to save PDF. If None, returns bytes.

    Returns:
        PDF file contents as bytes
    """
    indicators_df, geo_df = load_data()

    # Normalize code
    sgc_code = str(sgc_code).zfill(7)

    # Get community info
    comm_name, county = get_community_info(geo_df, sgc_code)

    # Determine latest year
    available_years = sorted(indicators_df["census_year"].unique())
    if census_year is None:
        census_year = max(available_years)
    elif census_year not in available_years:
        census_year = max(available_years)

    # Get community data
    comm_data = indicators_df[indicators_df["sgc_code"] == sgc_code]
    if comm_data.empty:
        raise ValueError(f"No data found for community {sgc_code}")

    # Ontario medians for comparison
    ont_avg = (
        indicators_df
        .groupby(["census_year", "indicator"])["value"]
        .median()
        .reset_index()
        .rename(columns={"value": "ont_median"})
    )

    # Build community lookup for peer names
    comm_lookup = {}
    for _, row in geo_df.iterrows():
        code = row["sgc_code"]
        name = row.get("geo_name", code)
        county_name = row.get("county", "")
        if pd.notna(county_name) and county_name:
            comm_lookup[code] = f"{name} ({county_name})"
        else:
            comm_lookup[code] = str(name)

    # ============================================================
    # BUILD THE PDF
    # ============================================================
    pdf = CommunityProfilePDF(comm_name, census_year, county)
    pdf.alias_nb_pages()
    pdf.add_page()

    # --- Cover Section ---
    pdf.ln(5)
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(*BRAND_DARK)
    pdf.cell(0, 12, comm_name, ln=True, align="C")

    if county:
        pdf.set_font("Helvetica", "", 12)
        pdf.set_text_color(*BRAND_ACCENT)
        pdf.cell(0, 8, f"{county} County, Ontario", ln=True, align="C")

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*MED_GREY)
    pdf.cell(0, 8, f"Census Profile Report - {census_year}", ln=True, align="C")
    pdf.ln(5)

    # --- Quick Stats Banner ---
    pdf.set_fill_color(*LIGHT_GREY)
    pdf.rect(10, pdf.get_y(), 190, 18, "F")
    quick_stats = ["population", "median_hh_income", "median_age", "unemployment_rate"]
    x_start = 12
    for slug in quick_stats:
        val_row = comm_data[
            (comm_data["indicator"] == slug) &
            (comm_data["census_year"] == census_year)
        ]
        val = val_row["value"].values[0] if len(val_row) > 0 else None
        meta = INDICATOR_META.get(slug, (slug, ""))
        formatted = _format_value(val, meta[1])

        pdf.set_xy(x_start, pdf.get_y() + 2)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*BRAND_ACCENT)
        pdf.cell(45, 5, meta[0], align="C")
        pdf.set_xy(x_start, pdf.get_y() + 5)
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(*BRAND_DARK)
        pdf.cell(45, 7, formatted, align="C")
        x_start += 47

    pdf.ln(22)

    # --- Section 1: Census Snapshot ---
    pdf.section_title("Census Snapshot")

    snapshot_data = comm_data[comm_data["census_year"] == census_year]

    headers = ["Indicator", f"Value ({census_year})", "Ontario Median", "vs Ontario"]
    rows = []
    for slug in SNAPSHOT_INDICATORS:
        meta = INDICATOR_META.get(slug, (slug, ""))
        val_row = snapshot_data[snapshot_data["indicator"] == slug]
        val = val_row["value"].values[0] if len(val_row) > 0 and pd.notna(val_row["value"].values[0]) else None

        ont_row = ont_avg[
            (ont_avg["census_year"] == census_year) &
            (ont_avg["indicator"] == slug)
        ]
        ont_val = ont_row["ont_median"].values[0] if len(ont_row) > 0 else None

        formatted_val = _format_value(val, meta[1])
        formatted_ont = _format_value(ont_val, meta[1])

        if val is not None and ont_val is not None and ont_val != 0:
            pct_diff = ((val - ont_val) / abs(ont_val)) * 100
            vs_ont = f"{pct_diff:+.1f}%"
        else:
            vs_ont = "--"

        rows.append([meta[0], formatted_val, formatted_ont, vs_ont])

    pdf.add_data_table(headers, rows, col_widths=[60, 40, 45, 45])
    pdf.ln(5)

    # --- Section 2: Census Trends ---
    pdf.section_title("Census Trends")

    for slug in TREND_INDICATORS:
        meta = INDICATOR_META.get(slug, (slug, ""))
        trend_data = comm_data[comm_data["indicator"] == slug].sort_values("census_year")

        if trend_data.empty:
            continue

        years = trend_data["census_year"].tolist()
        values = trend_data["value"].tolist()

        # Trend table row
        pdf.subsection_title(meta[0])

        trend_headers = [str(y) for y in years]
        trend_values = [_format_value(v, meta[1]) for v in values]

        if len(years) >= 2:
            first_val = values[0] if values[0] is not None and not np.isnan(values[0]) else None
            last_val = values[-1] if values[-1] is not None and not np.isnan(values[-1]) else None
            if first_val and last_val and first_val != 0:
                total_change = ((last_val - first_val) / abs(first_val)) * 100
                trend_headers.append(f"Change ({years[0]}-{years[-1]})")
                trend_values.append(f"{total_change:+.1f}%")

        widths = [190 / len(trend_headers)] * len(trend_headers)
        pdf.add_data_table(trend_headers, [trend_values], col_widths=widths)

        # Mini bar chart
        pdf.add_mini_bar_chart(slug, values, years)

    # --- Section 3: Demographics Profile ---
    if pdf.get_y() > 220:
        pdf.add_page()
    pdf.section_title("Demographics Profile")

    demo_indicators = ["pop_0_14", "pop_15_64", "pop_65_plus", "avg_hh_size", "pop_density"]
    demo_rows = []
    for slug in demo_indicators:
        meta = INDICATOR_META.get(slug, (slug, ""))
        val_row = snapshot_data[snapshot_data["indicator"] == slug]
        val = val_row["value"].values[0] if len(val_row) > 0 and pd.notna(val_row["value"].values[0]) else None

        # Get population for share calculation
        pop_row = snapshot_data[snapshot_data["indicator"] == "population"]
        pop_val = pop_row["value"].values[0] if len(pop_row) > 0 else None

        if slug in ("pop_0_14", "pop_15_64", "pop_65_plus") and val is not None and pop_val and pop_val > 0:
            share = val / pop_val * 100
            demo_rows.append([meta[0], f"{int(val):,}", f"{share:.1f}%"])
        elif val is not None:
            demo_rows.append([meta[0], _format_value(val, meta[1]), "--"])

    if demo_rows:
        pdf.add_data_table(["Indicator", "Value", "Share"], demo_rows, col_widths=[70, 60, 60])
    pdf.ln(5)

    # --- Section 4: Housing ---
    pdf.section_title("Housing Profile")

    housing_indicators = [
        "avg_dwelling_value", "shelter_cost_owned", "shelter_cost_rented",
        "unaffordable_renter_pct", "owner_households", "renter_households",
    ]
    housing_rows = []
    for slug in housing_indicators:
        meta = INDICATOR_META.get(slug, (slug, ""))
        val_row = snapshot_data[snapshot_data["indicator"] == slug]
        val = val_row["value"].values[0] if len(val_row) > 0 and pd.notna(val_row["value"].values[0]) else None
        ont_row = ont_avg[
            (ont_avg["census_year"] == census_year) &
            (ont_avg["indicator"] == slug)
        ]
        ont_val = ont_row["ont_median"].values[0] if len(ont_row) > 0 else None
        housing_rows.append([meta[0], _format_value(val, meta[1]), _format_value(ont_val, meta[1])])

    if housing_rows:
        pdf.add_data_table(["Indicator", "Local", "Ontario Median"], housing_rows, col_widths=[60, 65, 65])
    pdf.ln(5)

    # --- Section 5: Peer Communities --- (Red Team Fix Q3/Q4/Q18)
    if pdf.get_y() > 200:
        pdf.add_page()
    pdf.section_title("Similar Communities")

    top_peers, _ = get_peer_communities(indicators_df, sgc_code, census_year, n=5)

    if top_peers is not None and not top_peers.empty:
        pdf.body_text(
            f"Communities most similar to {comm_name} based on weighted Census indicators "
            f"(population, income, employment, demographics):"
        )

        peer_headers = ["Community", "Population", "Med. Income", "Unemp. Rate", "Med. Age"]
        peer_rows = []
        for peer_code, dist in top_peers.items():
            peer_name = comm_lookup.get(peer_code, peer_code)
            peer_snapshot = indicators_df[
                (indicators_df["sgc_code"] == peer_code) &
                (indicators_df["census_year"] == census_year)
            ]
            peer_vals = {}
            for slug in ["population", "median_hh_income", "unemployment_rate", "median_age"]:
                r = peer_snapshot[peer_snapshot["indicator"] == slug]
                # N3 Fix: deterministic .mean() instead of .values[0]
                val = r["value"].mean() if not r.empty else None
                peer_vals[slug] = val if pd.notna(val) else None

            # Fix Q18: use textwrap.shorten instead of brittle [:35] slicing
            safe_name = textwrap.shorten(peer_name, width=35, placeholder="...")
            peer_rows.append([
                safe_name,
                _format_value(peer_vals.get("population"), ""),
                _format_value(peer_vals.get("median_hh_income"), "$"),
                _format_value(peer_vals.get("unemployment_rate"), "%"),
                _format_value(peer_vals.get("median_age"), "years"),
            ])

        pdf.add_data_table(peer_headers, peer_rows, col_widths=[65, 30, 30, 30, 35])
    else:
        pdf.body_text("Insufficient data to compute peer communities.")
    pdf.ln(5)

    # --- Section 6: Data Sources ---
    if pdf.get_y() > 230:
        pdf.add_page()
    pdf.section_title("Data Sources & Methodology")
    pdf.body_text(
        "Data: Statistics Canada Census Profile (2006, 2011, 2016, 2021). "
        "Census Subdivisions (CSDs) include cities, towns, townships, and municipalities. "
        "Ontario Median represents the median value across all Ontario CSDs (not population-weighted). "
        "Peer similarity is computed using log-normalized, weighted z-score Euclidean distance across "
        "7 core Census indicators (population, income, unemployment, age, density, participation, "
        "household size), with population and income weighted 2x and demographics weighted 1.5x."
    )
    pdf.body_text(
        "2011 data has fewer indicators because income, labour, and education data was collected "
        "through the separate National Household Survey (NHS) that year. Some indicators may not "
        "be available for all years due to changes in Census methodology."
    )

    # --- Output ---
    pdf_bytes = pdf.output()

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "wb") as f:
            f.write(pdf_bytes)
        print(f"PDF saved to: {output_path}")

    return pdf_bytes


# CLI interface
def main():
    parser = argparse.ArgumentParser(description="Generate PDF Community Profile")
    parser.add_argument("--sgc", required=True, help="7-digit SGC code (e.g., 3523008)")
    parser.add_argument("--year", type=int, default=None, help="Census year (default: latest)")
    parser.add_argument("--output", default=None, help="Output file path (default: data/reports/)")
    args = parser.parse_args()

    sgc_code = str(args.sgc).zfill(7)
    output_path = args.output

    if output_path is None:
        report_dir = project_root / "data" / "reports"
        report_dir.mkdir(parents=True, exist_ok=True)
        output_path = str(report_dir / f"community_profile_{sgc_code}.pdf")

    generate_pdf(sgc_code, args.year, output_path)


if __name__ == "__main__":
    main()
